app_name = "square_integration"
app_title = "Square Integration"
app_publisher = "L&S Custom Tailors"
app_description = "Square payment capture for ERPNext Sales Invoices"
app_version = "1.0.0"
app_email = "carl@lstailors.com"
app_license = "MIT"
