// ERPNext DocType names used by L&S House (single source of truth).
export const DT = {
  LOCATION: "LSH Location",
  FABRIC_PRICING: "LSH Fabric Pricing",
  STYLE_LIBRARY: "LSH Style Library",
  PARKED_CART: "LSH Parked Cart",
  CUSTOMER_DOSSIER: "LSH Customer Dossier",
  CUSTOM_ORDER: "LSH Custom Order",
  CUSTOM_ORDER_GARMENT: "LSH Custom Order Garment",
  SMS_MESSAGE: "LSH SMS Message",
  APPROVAL_QUEUE: "LSH Approval Queue",
  APPROVAL_DECISION: "LSH Approval Decision",
  AGENT_BRIEF: "LSH Agent Brief",
  AGENT: "LSH Agent",
  AGENT_TASK: "LSH Agent Task",
  AGENT_EVENT: "LSH Agent Event",
  AGENT_COST: "LSH Agent Cost",
  AUDIT_LOG: "LSH Audit Log",
  CALL_LOG: "LSH Call Log",
  BRAIN_ENTRY: "LSH Brain Entry",
  PENDING_EMAIL_DRAFT: "LSH Pending Email Draft",
  APPOINTMENT: "LSH Appointment",
  ESCALATION: "LSH Escalation",
  CRON_JOB: "LSH Cron Job",
  AGENT_MESSAGE: "LSH Agent Message",
  PLAUD_CAPTURE: "LSH Plaud Capture",
  MMS_TEMPLATE: "LSH MMS Template",
  EMAIL_MESSAGE_LOG: "LSH Email Message Log",
  ORDER_REQUEST: "LSH Order Request",
  LS_TASK: "LSH Task",
  LS_TASK_ITEM: "LSH Task Item",
  CUSTOMER_MEETING: "LSH Customer Meeting",
  CONVERSATION_HANDOFF: "LSH Conversation Handoff",
  SOFIA_ACTIVITY_LOG: "LSH Sofia Activity Log",
  VOICE_APPROVAL_REQUEST: "LSH Voice Approval Request",
  TASK: "LSH Task",
  CUSTOMER_COMMUNICATION: "LSH Customer Communication",
  DOSSIER_OBSERVATION: "LSH Dossier Observation",
  MFG_ORDER: "LSH Mfg Order",
  PAYMENT_REQUEST: "LSH Payment Request",
  GEELUS_TRANSACTION: "LSH Geelus Transaction",
  CUSTOMER: "Customer",
  ADDRESS: "Address",
  EMPLOYEE: "Employee",
  FILE: "File",
} as const;

export const LSH_HOUSE_DOCTYPES = [
  "LSH Location",
  "LSH Fabric Pricing",
  "LSH Style Library",
  "LSH Parked Cart",
  "LSH Customer Dossier",
  "LSH Custom Order",
  "LSH Custom Order Garment",
  "LSH Approval Queue",
  "LSH Approval Decision",
  "LSH Agent Brief",
  "LSH Agent",
  "LSH Agent Task",
  "LSH Agent Event",
  "LSH Agent Cost",
  "LSH Audit Log",
  "LSH Call Log",
  "LSH Brain Entry",
  "LSH Pending Email Draft",
  "LSH Escalation",
  "LSH Cron Job",
  "LSH Agent Message",
  "LSH Plaud Capture",
  "LSH MMS Template",
  "LSH Email Message Log",
  "LSH Order Request",
  "LSH Task",
  "LSH Task Item",
  "LSH Customer Meeting",
  "LSH Conversation Handoff",
  "LSH Sofia Activity Log",
  "LSH Voice Approval Request",
  "LSH Customer Communication",
  "LSH Dossier Observation",
  "LSH Mfg Order",
  "LSH Payment Request",
  "LSH Geelus Transaction",
] as const;

export const LS_HOUSE_CROSS_MODULE_DOCTYPES = [
  "LSH Appointment",
  "LSH Appointment Type",
  "LSH Delivery",
  "LSH Delivery Timeline",
  "LSH Delivery Photo",
  "LSH Notification",
  "LSH Notification Recipient",
  "LSH SMS Message",
  "LSH SMS Settings",
] as const;

export const CRM_CROSS_MODULE_DOCTYPES = [
  "Communication Log",
  "Sophia Tool Call",
] as const;

export const CUSTOM_CROSS_MODULE_DOCTYPES = [
  "Compliance Document",
  "DocuSeal Template",
] as const;

export const LSH_DOCTYPE_INVENTORY = {
  "LSH House": LSH_HOUSE_DOCTYPES,
  "LS House": LS_HOUSE_CROSS_MODULE_DOCTYPES,
  CRM: CRM_CROSS_MODULE_DOCTYPES,
  Custom: CUSTOM_CROSS_MODULE_DOCTYPES,
} as const;
