// ERPNext DocType names used by L&S House (single source of truth).
export const DT = {
  LOCATION: "LSH Location",
  FABRIC_PRICING: "LSH Fabric Pricing",
  STYLE_LIBRARY: "LSH Style Library",
  PARKED_CART: "LSH Parked Cart",
  CUSTOMER_DOSSIER: "LSH Customer Dossier",
  CUSTOM_ORDER: "LSH Custom Order",
  CUSTOM_ORDER_GARMENT: "LSH Custom Order Garment",
  SMS_MESSAGE: "LSH SMS Message",
  APPROVAL_QUEUE: "LSH Approval Queue",
  /** Hermes dual-control gate (SPEC 067) — risk_level, amount, payload, decision_* */
  AGENT_APPROVAL: "LSH Agent Approval",
  APPROVAL_DECISION: "LSH Approval Decision",
  AGENT_BRIEF: "LSH Agent Brief",
  AGENT: "LSH Agent",
  AGENT_TASK: "LSH Agent Task",
  AGENT_EVENT: "LSH Agent Event",
  AGENT_COST: "LSH Agent Cost",
  AUDIT_LOG: "LSH Audit Log",
  CALL_LOG: "LSH Call Log",
  BRAIN_ENTRY: "LSH Brain Entry",
  PENDING_EMAIL_DRAFT: "LSH Pending Email Draft",
  APPOINTMENT: "LSH Appointment",
  ESCALATION: "LSH Escalation",
  CRON_JOB: "LSH Cron Job",
  AGENT_MESSAGE: "LSH Agent Message",
  PLAUD_CAPTURE: "LSH Plaud Capture",
  MMS_TEMPLATE: "LSH MMS Template",
  EMAIL_MESSAGE_LOG: "LSH Email Message Log",
  ORDER_REQUEST: "LSH Order Request",
  LS_TASK: "LSH Task",
  LS_TASK_ITEM: "LSH Task Item",
  CUSTOMER_MEETING: "LSH Customer Meeting",
  CONVERSATION_HANDOFF: "LSH Conversation Handoff",
  // One row per client phone (autoname field:client_phone). ai_enabled=0 means
  // a human holds the thread and the sofia-sms agent must stay silent.
  SMS_THREAD_CONTROL: "LSH SMS Thread Control",
  SOFIA_ACTIVITY_LOG: "LSH Sofia Activity Log",
  VOICE_APPROVAL_REQUEST: "LSH Voice Approval Request",
  TASK: "LSH Task",
  CUSTOMER_COMMUNICATION: "LSH Customer Communication",
  DOSSIER_OBSERVATION: "LSH Dossier Observation",
  MFG_ORDER: "LSH Mfg Order",
  PAYMENT_REQUEST: "LSH Payment Request",
  GEELUS_TRANSACTION: "LSH Geelus Transaction",
  CUSTOMER: "Customer",
  ADDRESS: "Address",
  EMPLOYEE: "Employee",
  FILE: "File",
  QC_INSPECTION: "LSH QC Inspection",
  MTM_PRO_ORDER: "MTMPro Order",
  FABRIC_SWATCH: "Fabric Swatch",
  ITEM_PRICE: "Item Price",
} as const;
