import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserQRCodeReader } from "@zxing/browser";
import "./style.css";

type Garment = { rowName:string; garmentId:string; qrToken:string; garmentType:string; description:string; currentLocation:string; status:string; completedBy:string; actualMinutes:number; work:string[] };
type Ticket = { ticket:string; customer:string; dueDate:string; dueTime:string; rush:boolean; workflowState:string; rackNumber:string; rackLocation:string; selectedGarment:string|null; garments:Garment[]; allDone:boolean };
type Tailor = { id:string; name:string };
type View = "home"|"scan"|"ticket"|"garment"|"transfer"|"complete";
const TIMES=[15,30,45,60,75,90,120,150,180];
const DESTS=["Stella","Hugo","Munro","Floor"] as const;
const labelLocation=(s:string)=>s.includes("Home Tailor One")?"Stella":s.includes("Home Tailor Two")?"Hugo":s.includes("Munro")?"Munro":s.includes("Work In Progress")?"Floor":s.replace(" - LSTNY","");
const timeLabel=(n:number)=>n<60?String(n):n%60?`${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`:`${n/60}h`;

async function api<T>(url:string, init?:RequestInit):Promise<T>{
  const res=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});
  const json=await res.json().catch(()=>({}));
  if(!res.ok) throw new Error(json?.error?.message||"Request failed");
  return json.data as T;
}

function App(){
  const [view,setView]=useState<View>("home"); const [ticket,setTicket]=useState<Ticket|null>(null);
  const [garment,setGarment]=useState<Garment|null>(null); const [queue,setQueue]=useState<any[]>([]);
  const [tailors,setTailors]=useState<Tailor[]>([]); const [chosenTailor,setChosenTailor]=useState("");
  const [minutes,setMinutes]=useState(30); const [note,setNote]=useState(""); const [destination,setDestination]=useState<typeof DESTS[number]>("Floor");
  const [rack,setRack]=useState(""); const [rackLocation,setRackLocation]=useState("NYC Showroom - LSTNY");
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const video=useRef<HTMLVideoElement>(null);
  useEffect(()=>{ api<any[]>("/api/floor/queue").then(setQueue).catch(()=>{}); api<Tailor[]>("/api/floor/tailors").then(setTailors).catch(()=>{}); },[]);
  useEffect(()=>{ if(view!=="scan"||!video.current)return; const reader=new BrowserQRCodeReader(); let controls:any; reader.decodeFromVideoDevice(undefined,video.current,(result)=>{ if(result){ controls?.stop(); openScan(result.getText()); }}).then(c=>controls=c).catch(()=>setError("Camera unavailable — enter the ticket below.")); return()=>controls?.stop(); },[view]);
  const sync=(t:Ticket, prefer?:View)=>{setTicket(t); const wanted=t.selectedGarment; const g=wanted?t.garments.find(x=>x.garmentId===wanted||x.rowName===wanted||x.qrToken===wanted):undefined; setGarment(g||null); setView(prefer||(g?"garment":"ticket"));};
  const openScan=async(value:string)=>{setBusy(true);setError("");try{sync(await api<Ticket>(`/api/floor/scan?value=${encodeURIComponent(value)}`));}catch(e:any){setError(e.message);setView("scan");}finally{setBusy(false);}};
  const manual=()=>{const value=prompt("Ticket, invoice, or garment tag");if(value)openScan(value);};
  const act=async(url:string,body:any,prefer:View)=>{setBusy(true);setError("");try{sync(await api<Ticket>(url,{method:"POST",body:JSON.stringify(body)}),prefer);}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  const selectGarment=(g:Garment,next:View)=>{setGarment(g);setView(next);setError("");};
  const back=()=>{setError(""); if(["transfer","complete"].includes(view))setView(ticket?.garments.length===1?"garment":"ticket");else if(["ticket","garment"].includes(view))setView("home");else setView("home");};
  const header=(title:string,sub:string)=><div className="chrome"><button className="back" onClick={back}>‹</button><div><h1>{title}</h1><small>{sub}</small></div></div>;
  const due=ticket?.dueDate?`${ticket.dueDate}${ticket.dueTime?` · ${ticket.dueTime.slice(0,5)}`:""}`:"No due date";
  const work=(g:Garment)=>g.work.join(" · ")||g.description||"Alteration work";

  if(view==="home") return <main className="app"><header className="brand"><div className="seal">L</div><div><h1>Floor</h1><small>{new Date().toLocaleDateString("en-US",{weekday:"short",day:"numeric",month:"short"})}</small></div><span className="today">Today</span></header><section className="kpis"><div><b>{queue.length}</b><small>Sched</small></div><div><b>{queue.filter(x=>x.workflow_state!=="Ready").length}</b><small>To-do</small></div><div className="green"><b>{queue.filter(x=>x.workflow_state==="Ready").length}</b><small>Ready</small></div><div><b>{queue.filter(x=>x.workflow_state==="In Progress").length}</b><small>Out</small></div></section><div className="section-title"><span>Queue</span><small>tap to open</small></div><section className="queue">{queue.map(q=><button className="queue-row" key={q.name} onClick={()=>openScan(q.name)}><i/><span><strong>{q.customer_name||"Client"}</strong><small>{q.name}</small></span><em>{q.workflow_state}<small>{q.due_date||""}</small></em></button>)}</section><div className="dock"><button className="primary scan-btn" onClick={()=>setView("scan")}>▣ &nbsp; Scan</button></div></main>;
  if(view==="scan") return <main className="app scanner"><video ref={video} playsInline muted/><div className="shade"/><div className="overlay">{header("Scan","Move or complete")}<section className="finder"><i/><i/><i/><i/><span/></section><div className="scan-copy"><b>{busy?"Looking up…":"Scan garment tag or master ticket"}</b><small>Hold steady · QR or barcode on hang tag</small>{error&&<p className="error">{error}</p>}</div><div className="dock"><button className="ghost wide" onClick={manual}>Enter ticket #</button></div></div></main>;
  if(!ticket||!garment&&view!=="ticket") return null;
  if(view==="garment"&&garment) return <main className="app">{header("Garment","Tag scanned")}<section className="content"><article className="hero"><label>{ticket.ticket}</label><h2>{ticket.customer}</h2><div className="work"><small>Work</small><strong>{garment.garmentType}</strong><p>{work(garment)}</p></div><div className="meta"><div><small>Due</small><b>{due}</b></div><div><small>Rush</small><b>{ticket.rush?"On":"Off"}</b></div></div><span className="where">● &nbsp; {labelLocation(garment.currentLocation)}</span></article><p className="hint">Two actions only — move it or finish it.</p></section>{error&&<p className="error fixed-error">{error}</p>}<div className="dock two"><button className="ghost" onClick={()=>setView("transfer")}>Transfer</button><button className="primary" onClick={()=>setView("complete")}>Complete</button></div></main>;
  if(view==="transfer"&&garment) return <main className="app">{header("Transfer","Where does it go?")}<div className="context"><span><b>{ticket.customer}</b><small>{garment.garmentType} · {work(garment)}</small></span><em>From<b>{labelLocation(garment.currentLocation)}</b></em></div><div className="section-title"><span>At-home · Floor</span></div><section className="options">{DESTS.map(d=><button key={d} className={destination===d?"selected":""} onClick={()=>setDestination(d)}><i>{d.slice(0,2).toUpperCase()}</i><span><b>{d}</b><small>{d==="Floor"?"Shop floor rack":"At home"}</small></span><em>✓</em></button>)}</section>{error&&<p className="error fixed-error">{error}</p>}<div className="dock"><button disabled={busy} className="primary wide" onClick={()=>act(`/api/floor/tickets/${ticket.ticket}/garments/${garment.garmentId}/transfer`,{destination},"garment")}>Confirm → {destination}</button></div></main>;
  if(view==="complete"&&garment) return <main className="app">{header("Complete","Log the work")}<div className="context simple"><span><b>{ticket.customer} · {garment.garmentType}</b><small>{ticket.ticket} · {due}</small></span></div><section className="form-scroll"><label>Tailor</label><div className="tailors">{tailors.map(t=><button className={chosenTailor===t.id?"selected":""} onClick={()=>setChosenTailor(t.id)} key={t.id}>{t.name}</button>)}</div><label>Time</label><div className="times">{TIMES.map(n=><button className={minutes===n?"selected":""} onClick={()=>setMinutes(n)} key={n}>{timeLabel(n)}</button>)}</div><label>Add note</label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional — facing clean, ready to hang…"/></section>{error&&<p className="error fixed-error">{error}</p>}<div className="dock"><button disabled={busy||!chosenTailor} className="primary wide" onClick={()=>act(`/api/floor/tickets/${ticket.ticket}/garments/${garment.garmentId}/complete`,{tailor:chosenTailor,minutes,note},ticket.garments.length===1?"garment":"ticket")}>Submit · {tailors.find(t=>t.id===chosenTailor)?.name||"Tailor"} · {timeLabel(minutes)}</button></div></main>;
  return <main className="app">{header("Ticket",`Master · ${ticket.garments.length} garments`)}<article className="ticket-head"><label>{ticket.ticket}</label><h2>{ticket.customer}</h2><div><span>{due}</span><span>Rush {ticket.rush?"on":"off"}</span><span>{ticket.garments.length} pcs</span></div></article><section className="garments">{ticket.garments.map((g,i)=><article className={g.status==="Ready"?"done":""} key={g.rowName}><header><span><b>{i+1} · {g.garmentType}</b><small>{work(g)}</small></span><em>{g.status==="Ready"?"Done":"Open"}</em></header><p>{labelLocation(g.currentLocation)}{g.actualMinutes?` · ${g.actualMinutes} min`:""}</p>{g.status==="Ready"?<button className="completed">Completed</button>:<div><button className="ghost" onClick={()=>selectGarment(g,"transfer")}>Transfer</button><button className="primary" onClick={()=>selectGarment(g,"complete")}>Complete</button></div>}</article>)}</section>{ticket.allDone&&<section className="rack"><input value={rack} onChange={e=>setRack(e.target.value)} placeholder="Rack #"/><input value={rackLocation} onChange={e=>setRackLocation(e.target.value)} placeholder="Rack location"/><button className="primary wide" disabled={busy||!rack} onClick={()=>act(`/api/floor/tickets/${ticket.ticket}/rack`,{rackNumber:rack,rackLocation},"ticket")}>Submit ticket → rack</button></section>}{error&&<p className="error fixed-error">{error}</p>}</main>;
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
